spring.application.name=plate-tracker
spring.profiles.default=local

spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false

spring.jackson.serialization.write-dates-as-timestamps=false

server.port=8080

plate.cors.allowed-origin-patterns=http://localhost:4200
